### ISSUE TITLE
一点小问题

### ISSUE THREAD

**Issue by Ayhan-Huang** [lwd-temp/MSD-Manual-Portable#1]
{C42FE853-FA02-41E2-AD2F-E9FF5A15D487}.html中，subTopic的UniqueId和json配置中的不一致

文件{59B811E8-6087-4942-88BD-926FD172DD51}.json，正常分娩的处理有两条Topic，对应两个html文件，但是内容一模一样，但默沙东也有两个网页，但是内容是不一样的。
"TopicId": "{2135724D-79FC-4480-B95E-11AD73EC4931}",
"TopicId": "{FF913577-1597-4A57-A169-8C3C41832BCD}", 实际默沙东也有两个网页，但是内容不一样。

 文件{1C13BE2E-E49F-42EB-9C9B-8DAD68F03564}.json，肠梗阻两条Topic，对应两个两个html文件，但是内容一模一样，沙东也有两个网页，但是内容是不一样的。

**Comment by lwd-temp** [comment]
在App上亦有此问题，这是MSD打包文档时的错误，无法在这里修复。
