### ISSUE TITLE
请问能下载兽医版吗

### ISSUE THREAD

**Issue by hypier** [lwd-temp/MSD-Manual-Portable#2]
请问能下载兽医版吗

**Comment by lwd-temp** [comment]
TODO

**Comment by lwd-temp** [comment]
看起来只有英文版？

**Comment by lwd-temp** [comment]
https://github.com/lwd-temp/MSD-Manual-Portable/commit/5028c2d17e51551693cfe1bf0c2cb3e7f4a4089c

**Comment by citrusjunoss** [comment]
你好，请问PetOwner 的版本名称怎么拼写

**Comment by SunsetMkt** [comment]
MSD似乎没有发布Pet Owner版本的App，所以没有对应的资源。
