### ISSUE TITLE
缺少json文件夹，项目无法启动

### ISSUE THREAD

**Issue by yoshiakiley** [lwd-temp/MSD-Manual-Portable#3]
启动的时候报错
FileNotFoundError: [Errno 2] No such file or directory: 'MSDProfessionalMedicalTopics/Json/sections.json'
然后查看MSDProfessionalMedicalTopics文件夹，发现并没有JSON文件夹

**Comment by lwd-temp** [comment]
Fixed https://github.com/lwd-temp/MSD-Manual-Portable/releases/tag/v3.3-eb45364d
